var names = ["raj", "kumar", "malluri"];
names.push("lali");
console.log(names);
var num = [1, 2, 3];
num.push(4);
console.log(num);
var mixed = ["raj", 1, "kumar", 2, "malluri", 3];
console.log(mixed);
mixed.push("lali");
mixed[1] = "raj";
console.log(mixed);
