var character;
var age;
var isLoggedIn;
age = 22;
character = "raj";
isLoggedIn = true;
console.log('character', character, 'age', age, 'isLoggedIn', isLoggedIn);
var ninjas = [];
ninjas.push('raj');
ninjas = ['kumar', 'malluri'];
console.log(ninjas);
var mixed = [];
mixed.push('raj');
mixed.push(1);
mixed.push(true);
console.log(mixed);
mixed = ['kumar', 2, true];
console.log(mixed);
